spring.application.name=backend

server.port = 8080

# debug = true
spring.devtools.restart.enabled=false
logging.level.org.springframework.security=DEBUG

spring.datasource.url=jdbc:postgresql://localhost:5432/ClgApp
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=1234

# spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB